services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
